Arrays

In [7]:
import numpy as np

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.full(5, 2)

array([2, 2, 2, 2, 2])

In [13]:
a = np.array([1,2,3,4,5])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0,1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multidimentional arrays

In [20]:
# MULTIDIMENTIONAL ARRAYS
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

TO ACCESS SINGLE VALUES THE SYNTAX IS ARRAY[ROW, COLUMN]

TO ACCESS ROWS THE SYNTAX IS ARRAY[ROW]

TO ACCESS COLUMNS THE SYNTAX IS ARRAY[:, COLUMN]

Randomly generated arrays

In [23]:
np.random.rand(5,2)

array([[0.87680132, 0.99444177],
       [0.89416372, 0.82945674],
       [0.10927297, 0.06082442],
       [0.48391225, 0.60049726],
       [0.64407602, 0.49203499]])

In [24]:
np.random.randn(5,2)

array([[-1.05780102, -1.17203175],
       [ 1.62698944,  1.33836586],
       [ 0.97615845,  0.23245158],
       [ 0.73869482,  0.29627492],
       [-0.39898665,  0.08697496]])

In [25]:
 np.random.randint(low=0, high=100, size=(5,2))

array([[ 6, 73],
       [28, 17],
       [48, 31],
       [95, 37],
       [22, 29]])

In [28]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [27]:
a+1

array([1, 2, 3, 4, 5])